<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HOME-PC" ignored="0" name="TestNG-Class" tests="8" failures="1" timestamp="25 May 2023 13:13:08 GMT" time="0.05" errors="0">
  <testcase name="verifyLoginSuccessfulWithValidCredentials" time="0.009" classname="com.automation.testcases.DataDrivenTest"/>
  <testcase name="verifyLoginUnsuccessfulWithInvalidCredentials" time="0.002" classname="com.automation.testcases.DataDrivenTest"/>
  <testcase name="verifyLoginUnsuccessfulWithInvalidCredentials" time="0.0" classname="com.automation.testcases.DataDrivenTest"/>
  <testcase name="verifyLoginUnsuccessfulWithInvalidCredentials" time="0.0" classname="com.automation.testcases.DataDrivenTest"/>
  <testcase name="verifyLoginUnsuccessfulWithInvalidCredentials" time="0.0" classname="com.automation.testcases.DataDrivenTest"/>
  <testcase name="verifyLoginUnsuccessfulWithInvalidCredentials" time="0.001" classname="com.automation.testcases.DataDrivenTest"/>
  <testcase name="verifyLoginUnsuccessfulWithInvalidCredentials" time="0.0" classname="com.automation.testcases.DataDrivenTest"/>
  <testcase name="verifyLoginUnsuccessfulWithInvalidCredentials" time="0.002" classname="com.automation.testcases.DataDrivenTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.automation.testcases.DataDrivenTest.verifyLoginUnsuccessfulWithInvalidCredentials(DataDrivenTest.java:19)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginUnsuccessfulWithInvalidCredentials -->
</testsuite> <!-- TestNG-Class -->
