<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="HOME-PC" name="com.automation.testcases.DataDrivenTest" tests="8" failures="1" timestamp="25 May 2023 13:13:08 GMT" time="0.014" errors="0">
  <testcase name="verifyLoginUnsuccessfulWithInvalidCredentials" time="0.000" classname="com.automation.testcases.DataDrivenTest"/>
  <testcase name="verifyLoginUnsuccessfulWithInvalidCredentials" time="0.001" classname="com.automation.testcases.DataDrivenTest"/>
  <testcase name="verifyLoginUnsuccessfulWithInvalidCredentials" time="0.002" classname="com.automation.testcases.DataDrivenTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at com.automation.testcases.DataDrivenTest.verifyLoginUnsuccessfulWithInvalidCredentials(DataDrivenTest.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase> <!-- verifyLoginUnsuccessfulWithInvalidCredentials -->
  <testcase name="verifyLoginUnsuccessfulWithInvalidCredentials" time="0.000" classname="com.automation.testcases.DataDrivenTest"/>
  <testcase name="verifyLoginUnsuccessfulWithInvalidCredentials" time="0.000" classname="com.automation.testcases.DataDrivenTest"/>
  <testcase name="verifyLoginSuccessfulWithValidCredentials" time="0.009" classname="com.automation.testcases.DataDrivenTest"/>
  <testcase name="verifyLoginUnsuccessfulWithInvalidCredentials" time="0.002" classname="com.automation.testcases.DataDrivenTest"/>
  <testcase name="verifyLoginUnsuccessfulWithInvalidCredentials" time="0.000" classname="com.automation.testcases.DataDrivenTest"/>
</testsuite> <!-- com.automation.testcases.DataDrivenTest -->
